### ISSUE TITLE
 FS<2> <page-style>

### ISSUE THREAD

**Issue by yadetagetachew** [yadetagetachew/carousel#4]
### Feature
Create old school tv style with pngs saved from computer and figma

 ### File name
old.html

### Task
    - [ ] 1. _add classic tv skeleton
    - [ ] 2. _add cartoon family siting on couch 
    - [ ] 3. _make sure png's are scalable
