### ISSUE TITLE
 FS<2.5> <page-style>

### ISSUE THREAD

**Issue by yadetagetachew** [yadetagetachew/carousel#5]
### Feature
Create flat screen tv style with pngs saved from computer and figma

 ### File name
new.html

### Task
    - [ ] 1. _add flat screen tv skeleton
    - [ ] 2. _add family siting on couch 
    - [ ] 3. _make sure png's are scalable
